# Generated by Django 5.2.7 on 2025-10-13 12:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BannerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Banner olarak kullanılacak görsel. Önerilen boyut: 1920x1080 piksel (16:9 en-boy oranı). Tüm banner görselleri aynı boyutta olmalıdır.",
                        upload_to="banner/",
                        verbose_name="Banner Görseli",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Görsel için erişilebilirlik metni",
                        max_length=255,
                        verbose_name="Alternatif Metin",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True,
                        help_text="Banner üzerinde gösterilecek buton metni (boş bırakılırsa buton gösterilmez)",
                        max_length=100,
                        verbose_name="Buton Metni",
                    ),
                ),
                (
                    "button_link",
                    models.URLField(
                        blank=True,
                        help_text="Butonun yönlendireceği URL",
                        verbose_name="Buton Bağlantısı",
                    ),
                ),
                (
                    "button_position",
                    models.CharField(
                        choices=[
                            ("top-left", "Üst Sol"),
                            ("top-center", "Üst Orta"),
                            ("top-right", "Üst Sağ"),
                            ("middle-left", "Orta Sol"),
                            ("middle-center", "Orta"),
                            ("middle-right", "Orta Sağ"),
                            ("bottom-left", "Alt Sol"),
                            ("bottom-center", "Alt Orta"),
                            ("bottom-right", "Alt Sağ"),
                        ],
                        default="middle-center",
                        help_text="Butonun banner üzerindeki konumu",
                        max_length=20,
                        verbose_name="Buton Konumu",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturma Tarihi",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Banner Görseli",
                "verbose_name_plural": "Banner Görselleri",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Construction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        help_text="İnşaat proje adı",
                        max_length=255,
                        verbose_name="Proje Adı",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="URL Yolu"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Proje açıklaması", verbose_name="Proje Açıklaması"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Proje konumu", max_length=255, verbose_name="Konum"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planlamada"),
                            ("ongoing", "Devam Ediyor"),
                            ("completed", "Tamamlandı"),
                        ],
                        default="ongoing",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Başlangıç Tarihi")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bitiş Tarihi"
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        help_text="Ana proje resmi",
                        upload_to="construction/",
                        verbose_name="Ana Resim",
                    ),
                ),
                (
                    "image_alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Resim Alt Yazısı"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturma Tarihi",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Meta Başlık"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta Açıklama"
                    ),
                ),
            ],
            options={
                "verbose_name": "İnşaat Projesi",
                "verbose_name_plural": "İnşaat Projeleri",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ad Soyad")),
                ("email", models.EmailField(max_length=254, verbose_name="E-posta")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=200, verbose_name="Konu"),
                ),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Gönderim Tarihi",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Okundu")),
            ],
            options={
                "verbose_name": "İletişim Mesajı",
                "verbose_name_plural": "İletişim Mesajları",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="CustomSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Başlık")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alt Başlık"
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="İçerik")),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("text_only", "Sadece Metin"),
                            ("image_left", "Resim Solda"),
                            ("image_right", "Resim Sağda"),
                            ("image_center", "Resim Ortada"),
                            ("cards", "Kartlar"),
                            ("about_section", "Hakkımızda Bölümü"),
                            ("services", "Hizmetler"),
                        ],
                        default="text_only",
                        max_length=20,
                        verbose_name="Düzen",
                    ),
                ),
                (
                    "text_alignment",
                    models.CharField(
                        choices=[("left", "Sol"), ("center", "Orta"), ("right", "Sağ")],
                        default="left",
                        max_length=10,
                        verbose_name="Metin Hizalama",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="custom_sections/",
                        verbose_name="Ana Resim",
                    ),
                ),
                (
                    "image_alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Resim Alt Yazısı"
                    ),
                ),
                (
                    "card_title_1",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Kart 1 Başlık"
                    ),
                ),
                (
                    "card_content_1",
                    models.TextField(blank=True, verbose_name="Kart 1 İçerik"),
                ),
                (
                    "card_image_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="custom_sections/cards/",
                        verbose_name="Kart 1 Resim",
                    ),
                ),
                (
                    "card_title_2",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Kart 2 Başlık"
                    ),
                ),
                (
                    "card_content_2",
                    models.TextField(blank=True, verbose_name="Kart 2 İçerik"),
                ),
                (
                    "card_image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="custom_sections/cards/",
                        verbose_name="Kart 2 Resim",
                    ),
                ),
                (
                    "card_title_3",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Kart 3 Başlık"
                    ),
                ),
                (
                    "card_content_3",
                    models.TextField(blank=True, verbose_name="Kart 3 İçerik"),
                ),
                (
                    "card_image_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="custom_sections/cards/",
                        verbose_name="Kart 3 Resim",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        blank=True,
                        help_text="HEX renk kodu (örn: #ffffff)",
                        max_length=20,
                        verbose_name="Arka Plan Rengi",
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        blank=True,
                        help_text="HEX renk kodu (örn: #000000)",
                        max_length=20,
                        verbose_name="Metin Rengi",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturma Tarihi",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Özel Bölüm",
                "verbose_name_plural": "Özel Bölümler",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="SEO için optimize edilmiş emlak başlığı",
                        max_length=255,
                        verbose_name="Başlık",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="URL Yolu"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detaylı emlak açıklaması", verbose_name="Açıklama"
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Daire"),
                            ("house", "Ev"),
                            ("villa", "Villa"),
                            ("land", "Arsa"),
                            ("commercial", "Ticari"),
                            ("office", "Ofis"),
                        ],
                        default="apartment",
                        max_length=50,
                        verbose_name="Emlak Tipi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("sale", "Satılık"), ("rent", "Kiralık")],
                        default="sale",
                        max_length=10,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Türk Lirası cinsinden fiyat",
                        max_digits=12,
                        verbose_name="Fiyat",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Emlak konumu (şehir, ilçe)",
                        max_length=255,
                        verbose_name="Konum",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Adres"
                    ),
                ),
                (
                    "bedrooms",
                    models.IntegerField(
                        default=0,
                        help_text="Yatak odası adedi",
                        verbose_name="Yatak Odası Sayısı",
                    ),
                ),
                (
                    "bathrooms",
                    models.IntegerField(
                        default=0, help_text="Banyo adedi", verbose_name="Banyo Sayısı"
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Metrekare cinsinden alan",
                        max_digits=10,
                        verbose_name="Alan (m²)",
                    ),
                ),
                (
                    "floor",
                    models.IntegerField(
                        blank=True,
                        help_text="Kat numarası",
                        null=True,
                        verbose_name="Kat",
                    ),
                ),
                (
                    "building_age",
                    models.IntegerField(
                        blank=True,
                        help_text="Bina yaşı (yıl)",
                        null=True,
                        verbose_name="Bina Yaşı",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        help_text="Ana emlak resmi",
                        upload_to="listings/",
                        verbose_name="Ana Resim",
                    ),
                ),
                (
                    "image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Ana resim için SEO alt yazısı",
                        max_length=255,
                        verbose_name="Resim Alt Yazısı",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Web sitesinde göster",
                        verbose_name="Aktif",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Ana sayfada göster",
                        verbose_name="Öne Çıkan",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturma Tarihi",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO meta başlığı",
                        max_length=60,
                        verbose_name="Meta Başlık",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="SEO meta açıklaması",
                        max_length=160,
                        verbose_name="Meta Açıklama",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emlak İlanı",
                "verbose_name_plural": "Emlak İlanları",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Başlık")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alt Başlık"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturma Tarihi",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Referans",
                "verbose_name_plural": "Referanslar",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SEOSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("home", "Anasayfa"),
                            ("listings", "İlanlar"),
                            ("construction", "İnşaatlar"),
                            ("references", "Referanslar"),
                            ("contact", "İletişim"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Sayfa Türü",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Tarayıcı sekmesinde görünen başlık (en fazla 60 karakter)",
                        max_length=60,
                        verbose_name="Meta Başlık",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Arama motorlarında görünen açıklama (en fazla 160 karakter)",
                        max_length=160,
                        verbose_name="Meta Açıklama",
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True,
                        help_text="Sosyal medya platformlarında paylaşıldığında görünen başlık",
                        max_length=60,
                        verbose_name="Open Graph Başlık",
                    ),
                ),
                (
                    "og_description",
                    models.CharField(
                        blank=True,
                        help_text="Sosyal medya platformlarında paylaşıldığında görünen açıklama",
                        max_length=255,
                        verbose_name="Open Graph Açıklama",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Sosyal medya platformlarında paylaşıldığında görünen görsel",
                        null=True,
                        upload_to="seo/",
                        verbose_name="Open Graph Görseli",
                    ),
                ),
                (
                    "og_image_alt",
                    models.CharField(
                        blank=True,
                        help_text="Open Graph görseli için alternatif metin",
                        max_length=255,
                        verbose_name="Open Graph Görsel Açıklaması",
                    ),
                ),
                (
                    "structured_data",
                    models.TextField(
                        blank=True,
                        help_text="Sayfa için özel JSON-LD yapılandırılmış veri",
                        verbose_name="Yapılandırılmış Veri (JSON-LD)",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Ayarı",
                "verbose_name_plural": "SEO Ayarları",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Sitenizin logosunu yükleyin",
                        upload_to="site/",
                        verbose_name="Site Logosu",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Tarayıcı sekmesinde görünen favicon (genellikle 32x32 piksel)",
                        upload_to="site/",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Telefon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-posta"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=500, verbose_name="Adres"),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Vergi Numarası"
                    ),
                ),
                (
                    "tax_office",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Vergi Dairesi"
                    ),
                ),
                (
                    "map_embed_code",
                    models.TextField(
                        blank=True,
                        help_text="Google Maps embed kodunu buraya yapıştırın",
                        verbose_name="Harita Embed Kodu",
                    ),
                ),
                (
                    "map_latitude",
                    models.CharField(
                        blank=True,
                        help_text="Harita konumunun enlem değeri",
                        max_length=20,
                        verbose_name="Enlem (Latitude)",
                    ),
                ),
                (
                    "map_longitude",
                    models.CharField(
                        blank=True,
                        help_text="Harita konumunun boylam değeri",
                        max_length=20,
                        verbose_name="Boylam (Longitude)",
                    ),
                ),
                (
                    "google_maps_api_key",
                    models.CharField(
                        blank=True,
                        help_text="Google Maps API anahtarınızı buraya ekleyin",
                        max_length=100,
                        verbose_name="Google Maps API Anahtarı",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, verbose_name="Facebook URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram URL"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="Twitter URL"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, verbose_name="LinkedIn URL"),
                ),
                (
                    "google_search_console_verification",
                    models.CharField(
                        blank=True,
                        help_text="Google Search Console için meta tag veya HTML doğrulama kodu",
                        max_length=500,
                        verbose_name="Google Search Console Doğrulama Kodu",
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Analytics için izleme ID (örn: UA-XXXXXXXX-X veya G-XXXXXXXXXX)",
                        max_length=50,
                        verbose_name="Google Analytics ID",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Ayarları",
                "verbose_name_plural": "Site Ayarları",
            },
        ),
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "homepage_template",
                    models.CharField(
                        choices=[
                            ("template1", "Template 1 - Large Banner"),
                            ("template2", "Template 2 - Minimal"),
                            ("template3", "Template 3 - Featured Focus"),
                            ("template4", "Template 4 - Content Rich"),
                        ],
                        default="template1",
                        help_text="Anasayfa için kullanılacak şablonu seçin",
                        max_length=20,
                        verbose_name="Anasayfa Şablonu",
                    ),
                ),
                (
                    "show_listings_page",
                    models.BooleanField(
                        default=True,
                        help_text="Header menüsünde İlanlar sayfası linkini göster",
                        verbose_name="İlanlar Sayfasını Göster",
                    ),
                ),
                (
                    "show_construction_page",
                    models.BooleanField(
                        default=True,
                        help_text="Header menüsünde İnşaatlar sayfası linkini göster",
                        verbose_name="İnşaatlar Sayfasını Göster",
                    ),
                ),
                (
                    "show_references_page",
                    models.BooleanField(
                        default=True,
                        help_text="Header menüsünde Referanslar sayfası linkini göster",
                        verbose_name="Referanslar Sayfasını Göster",
                    ),
                ),
                (
                    "show_contact_page",
                    models.BooleanField(
                        default=True,
                        help_text="Header menüsünde İletişim sayfası linkini göster",
                        verbose_name="İletişim Sayfasını Göster",
                    ),
                ),
                (
                    "show_search_bar",
                    models.BooleanField(
                        default=True, verbose_name="Arama Çubuğunu Göster"
                    ),
                ),
                (
                    "show_stats_section",
                    models.BooleanField(
                        default=True, verbose_name="İstatistikleri Göster"
                    ),
                ),
                (
                    "show_featured_listings",
                    models.BooleanField(
                        default=True, verbose_name="Öne Çıkan İlanları Göster"
                    ),
                ),
                (
                    "show_features_section",
                    models.BooleanField(
                        default=True, verbose_name="Özellikler Bölümünü Göster"
                    ),
                ),
                (
                    "show_testimonials",
                    models.BooleanField(
                        default=True, verbose_name="Müşteri Yorumlarını Göster"
                    ),
                ),
                (
                    "show_recent_listings",
                    models.BooleanField(
                        default=True, verbose_name="Son İlanları Göster"
                    ),
                ),
                (
                    "show_contact_info",
                    models.BooleanField(
                        default=True, verbose_name="İletişim Bilgilerini Göster"
                    ),
                ),
                (
                    "show_social_media",
                    models.BooleanField(
                        default=True, verbose_name="Sosyal Medya Bağlantılarını Göster"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "banner_images",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Anasayfa banner'ında gösterilmesini istediğiniz görselleri seçin",
                        to="properties.bannerimage",
                        verbose_name="Banner Görselleri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ana Sayfa Ayarları",
                "verbose_name_plural": "Ana Sayfa Ayarları",
            },
        ),
        migrations.CreateModel(
            name="ConstructionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="construction/gallery/", verbose_name="Resim"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alt Yazı"
                    ),
                ),
                (
                    "caption",
                    models.CharField(blank=True, max_length=255, verbose_name="Başlık"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yüklenme Tarihi"
                    ),
                ),
                (
                    "construction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.construction",
                        verbose_name="İnşaat Projesi",
                    ),
                ),
            ],
            options={
                "verbose_name": "İnşaat Resmi",
                "verbose_name_plural": "İnşaat Resimleri",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="listings/gallery/", verbose_name="Resim"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alt Yazı"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yüklenme Tarihi"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.listing",
                        verbose_name="İlan",
                    ),
                ),
            ],
            options={
                "verbose_name": "İlan Resmi",
                "verbose_name_plural": "İlan Resimleri",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ReferenceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="references/images/", verbose_name="Resim"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alternatif Metin"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.reference",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referans Resmi",
                "verbose_name_plural": "Referans Resimleri",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ReferenceVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to="references/videos/", verbose_name="Video"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Video Başlığı"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="properties.reference",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referans Videosu",
                "verbose_name_plural": "Referans Videoları",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VisibleCustomSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Görünüm Sırası"
                    ),
                ),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.about",
                    ),
                ),
                (
                    "custom_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.customsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Görünür Özel Bölüm",
                "verbose_name_plural": "Görünür Özel Bölümler",
                "ordering": ["order"],
                "unique_together": {("about", "custom_section")},
            },
        ),
    ]
