# Generated by Django 5.2.7 on 2025-10-11 14:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="About Us", max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField(help_text="Main about page content")),
                (
                    "mission",
                    models.TextField(blank=True, help_text="Company mission statement"),
                ),
                ("vision", models.TextField(blank=True, help_text="Company vision")),
                (
                    "main_image",
                    models.ImageField(
                        help_text="Main about page image", upload_to="about/"
                    ),
                ),
                ("image_alt_text", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("meta_title", models.CharField(blank=True, max_length=60)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Page",
                "verbose_name_plural": "About Page",
            },
        ),
        migrations.CreateModel(
            name="Construction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        help_text="Construction project name", max_length=255
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField(help_text="Project description")),
                (
                    "location",
                    models.CharField(help_text="Project location", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                        ],
                        default="ongoing",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "main_image",
                    models.ImageField(
                        help_text="Main project image", upload_to="construction/"
                    ),
                ),
                ("image_alt_text", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("meta_title", models.CharField(blank=True, max_length=60)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
            ],
            options={
                "verbose_name": "Construction Project",
                "verbose_name_plural": "Construction Projects",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="SEO-optimized property title", max_length=255
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "description",
                    models.TextField(help_text="Detailed property description"),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("villa", "Villa"),
                            ("land", "Land"),
                            ("commercial", "Commercial"),
                            ("office", "Office"),
                        ],
                        default="apartment",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("sale", "For Sale"), ("rent", "For Rent")],
                        default="sale",
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in currency", max_digits=12
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Property location (city, district)", max_length=255
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "bedrooms",
                    models.IntegerField(default=0, help_text="Number of bedrooms"),
                ),
                (
                    "bathrooms",
                    models.IntegerField(default=0, help_text="Number of bathrooms"),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Area in square meters",
                        max_digits=10,
                    ),
                ),
                (
                    "floor",
                    models.IntegerField(
                        blank=True, help_text="Floor number", null=True
                    ),
                ),
                (
                    "building_age",
                    models.IntegerField(
                        blank=True, help_text="Building age in years", null=True
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        help_text="Main property image", upload_to="listings/"
                    ),
                ),
                (
                    "image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="SEO alt text for main image",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Display on website"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="Show on homepage"),
                ),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, help_text="SEO meta title", max_length=60
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, help_text="SEO meta description", max_length=160
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Listing",
                "verbose_name_plural": "Property Listings",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="ConstructionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="construction/gallery/")),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("order", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "construction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.construction",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="listings/gallery/")),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("order", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.listing",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
