# Generated by Django 5.2.7 on 2025-10-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannerimage",
            name="alt_text_color",
            field=models.CharField(
                blank=True,
                default="#ffffff",
                help_text="Alternatif metin rengi (HEX formatında, örn: #ffffff)",
                max_length=7,
                verbose_name="Alternatif Metin Rengi",
            ),
        ),
        migrations.AddField(
            model_name="bannerimage",
            name="alt_text_position",
            field=models.CharField(
                choices=[
                    ("top-left", "Üst Sol"),
                    ("top-center", "Üst Orta"),
                    ("top-right", "Üst Sağ"),
                    ("middle-left", "Orta Sol"),
                    ("middle-center", "Orta"),
                    ("middle-right", "Orta Sağ"),
                    ("bottom-left", "Alt Sol"),
                    ("bottom-center", "Alt Orta"),
                    ("bottom-right", "Alt Sağ"),
                ],
                default="bottom-center",
                help_text="Alternatif metnin banner üzerindeki konumu",
                max_length=20,
                verbose_name="Alternatif Metin Konumu",
            ),
        ),
        migrations.AddField(
            model_name="bannerimage",
            name="button_background_color",
            field=models.CharField(
                blank=True,
                default="#6a11cb",
                help_text="Butonun arka plan rengi (HEX formatında, örn: #6a11cb)",
                max_length=7,
                verbose_name="Buton Arka Plan Rengi",
            ),
        ),
        migrations.AddField(
            model_name="bannerimage",
            name="button_text_color",
            field=models.CharField(
                blank=True,
                default="#ffffff",
                help_text="Butonun metin rengi (HEX formatında, örn: #ffffff)",
                max_length=7,
                verbose_name="Buton Metin Rengi",
            ),
        ),
        migrations.AddField(
            model_name="bannerimage",
            name="overlay_color",
            field=models.CharField(
                blank=True,
                default="rgba(0, 0, 0, 0.35)",
                help_text="Görsel üzerindeki kaplama rengi (RGBA formatında, örn: rgba(0, 0, 0, 0.35))",
                max_length=25,
                verbose_name="Kaplama Rengi",
            ),
        ),
    ]
