# Generated by Django 5.2.7 on 2025-10-13 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customsection",
            options={
                "verbose_name": "Özel Bölüm",
                "verbose_name_plural": "Özel Bölümler",
            },
        ),
        migrations.RemoveField(
            model_name="customsection",
            name="order",
        ),
    ]
