# Generated by Django 5.2.7 on 2025-10-11 15:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={
                "verbose_name": "Hakkımızda Sayfası",
                "verbose_name_plural": "Hakkımızda Sayfası",
            },
        ),
        migrations.AlterModelOptions(
            name="construction",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "İnşaat Projesi",
                "verbose_name_plural": "İnşaat Projeleri",
            },
        ),
        migrations.AlterModelOptions(
            name="constructionimage",
            options={
                "ordering": ["order"],
                "verbose_name": "İnşaat Resmi",
                "verbose_name_plural": "İnşaat Resimleri",
            },
        ),
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "İletişim Mesajı",
                "verbose_name_plural": "İletişim Mesajları",
            },
        ),
        migrations.AlterModelOptions(
            name="listing",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "Emlak İlanı",
                "verbose_name_plural": "Emlak İlanları",
            },
        ),
        migrations.AlterModelOptions(
            name="listingimage",
            options={
                "ordering": ["order"],
                "verbose_name": "İlan Resmi",
                "verbose_name_plural": "İlan Resimleri",
            },
        ),
        migrations.AlterField(
            model_name="about",
            name="address",
            field=models.CharField(blank=True, max_length=500, verbose_name="Adres"),
        ),
        migrations.AlterField(
            model_name="about",
            name="content",
            field=models.TextField(
                help_text="Ana hakkımızda sayfa içeriği", verbose_name="İçerik"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-posta"),
        ),
        migrations.AlterField(
            model_name="about",
            name="facebook_url",
            field=models.URLField(blank=True, verbose_name="Facebook URL"),
        ),
        migrations.AlterField(
            model_name="about",
            name="image_alt_text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Resim Alt Yazısı"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="instagram_url",
            field=models.URLField(blank=True, verbose_name="Instagram URL"),
        ),
        migrations.AlterField(
            model_name="about",
            name="linkedin_url",
            field=models.URLField(blank=True, verbose_name="LinkedIn URL"),
        ),
        migrations.AlterField(
            model_name="about",
            name="main_image",
            field=models.ImageField(
                help_text="Ana hakkımızda sayfa resmi",
                upload_to="about/",
                verbose_name="Ana Resim",
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="meta_description",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Meta Açıklama"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="meta_title",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Meta Başlık"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="mission",
            field=models.TextField(
                blank=True, help_text="Şirket misyon beyanı", verbose_name="Misyon"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="about",
            name="subtitle",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Alt Başlık"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="title",
            field=models.CharField(
                default="Hakkımızda", max_length=255, verbose_name="Başlık"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="twitter_url",
            field=models.URLField(blank=True, verbose_name="Twitter URL"),
        ),
        migrations.AlterField(
            model_name="about",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Güncelleme Tarihi"),
        ),
        migrations.AlterField(
            model_name="about",
            name="vision",
            field=models.TextField(
                blank=True, help_text="Şirket vizyonu", verbose_name="Vizyon"
            ),
        ),
        migrations.AlterField(
            model_name="construction",
            name="created_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Oluşturma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="construction",
            name="description",
            field=models.TextField(
                help_text="Proje açıklaması", verbose_name="Proje Açıklaması"
            ),
        ),
        migrations.AlterField(
            model_name="construction",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Bitiş Tarihi"),
        ),
        migrations.AlterField(
            model_name="construction",
            name="image_alt_text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Resim Alt Yazısı"
            ),
        ),
        migrations.AlterField(
            model_name="construction",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif"),
        ),
        migrations.AlterField(
            model_name="construction",
            name="location",
            field=models.CharField(
                help_text="Proje konumu", max_length=255, verbose_name="Konum"
            ),
        ),
        migrations.AlterField(
            model_name="construction",
            name="main_image",
            field=models.ImageField(
                help_text="Ana proje resmi",
                upload_to="construction/",
                verbose_name="Ana Resim",
            ),
        ),
        migrations.AlterField(
            model_name="construction",
            name="meta_description",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Meta Açıklama"
            ),
        ),
        migrations.AlterField(
            model_name="construction",
            name="meta_title",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Meta Başlık"
            ),
        ),
        migrations.AlterField(
            model_name="construction",
            name="project_name",
            field=models.CharField(
                help_text="İnşaat proje adı", max_length=255, verbose_name="Proje Adı"
            ),
        ),
        migrations.AlterField(
            model_name="construction",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="URL Yolu"
            ),
        ),
        migrations.AlterField(
            model_name="construction",
            name="start_date",
            field=models.DateField(verbose_name="Başlangıç Tarihi"),
        ),
        migrations.AlterField(
            model_name="construction",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Planlamada"),
                    ("ongoing", "Devam Ediyor"),
                    ("completed", "Tamamlandı"),
                ],
                default="ongoing",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AlterField(
            model_name="constructionimage",
            name="alt_text",
            field=models.CharField(blank=True, max_length=255, verbose_name="Alt Yazı"),
        ),
        migrations.AlterField(
            model_name="constructionimage",
            name="caption",
            field=models.CharField(blank=True, max_length=255, verbose_name="Başlık"),
        ),
        migrations.AlterField(
            model_name="constructionimage",
            name="construction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="properties.construction",
                verbose_name="İnşaat Projesi",
            ),
        ),
        migrations.AlterField(
            model_name="constructionimage",
            name="image",
            field=models.ImageField(
                upload_to="construction/gallery/", verbose_name="Resim"
            ),
        ),
        migrations.AlterField(
            model_name="constructionimage",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Sıra"),
        ),
        migrations.AlterField(
            model_name="constructionimage",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yüklenme Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="created_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Gönderim Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="E-posta"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="Okundu"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="message",
            field=models.TextField(verbose_name="Mesaj"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Ad Soyad"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(blank=True, max_length=200, verbose_name="Konu"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="address",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Adres"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="area",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Metrekare cinsinden alan",
                max_digits=10,
                verbose_name="Alan (m²)",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="bathrooms",
            field=models.IntegerField(
                default=0, help_text="Banyo adedi", verbose_name="Banyo Sayısı"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="bedrooms",
            field=models.IntegerField(
                default=0,
                help_text="Yatak odası adedi",
                verbose_name="Yatak Odası Sayısı",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="building_age",
            field=models.IntegerField(
                blank=True,
                help_text="Bina yaşı (yıl)",
                null=True,
                verbose_name="Bina Yaşı",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="created_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Oluşturma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.TextField(
                help_text="Detaylı emlak açıklaması", verbose_name="Açıklama"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="floor",
            field=models.IntegerField(
                blank=True, help_text="Kat numarası", null=True, verbose_name="Kat"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image_alt_text",
            field=models.CharField(
                blank=True,
                help_text="Ana resim için SEO alt yazısı",
                max_length=255,
                verbose_name="Resim Alt Yazısı",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Web sitesinde göster", verbose_name="Aktif"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Ana sayfada göster", verbose_name="Öne Çıkan"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="location",
            field=models.CharField(
                help_text="Emlak konumu (şehir, ilçe)",
                max_length=255,
                verbose_name="Konum",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="main_image",
            field=models.ImageField(
                help_text="Ana emlak resmi",
                upload_to="listings/",
                verbose_name="Ana Resim",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="SEO meta açıklaması",
                max_length=160,
                verbose_name="Meta Açıklama",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="SEO meta başlığı",
                max_length=60,
                verbose_name="Meta Başlık",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Türk Lirası cinsinden fiyat",
                max_digits=12,
                verbose_name="Fiyat",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("apartment", "Daire"),
                    ("house", "Ev"),
                    ("villa", "Villa"),
                    ("land", "Arsa"),
                    ("commercial", "Ticari"),
                    ("office", "Ofis"),
                ],
                default="apartment",
                max_length=50,
                verbose_name="Emlak Tipi",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="URL Yolu"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[("sale", "Satılık"), ("rent", "Kiralık")],
                default="sale",
                max_length=10,
                verbose_name="Durum",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="title",
            field=models.CharField(
                help_text="SEO için optimize edilmiş emlak başlığı",
                max_length=255,
                verbose_name="Başlık",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Güncelleme Tarihi"),
        ),
        migrations.AlterField(
            model_name="listingimage",
            name="alt_text",
            field=models.CharField(blank=True, max_length=255, verbose_name="Alt Yazı"),
        ),
        migrations.AlterField(
            model_name="listingimage",
            name="image",
            field=models.ImageField(
                upload_to="listings/gallery/", verbose_name="Resim"
            ),
        ),
        migrations.AlterField(
            model_name="listingimage",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="properties.listing",
                verbose_name="İlan",
            ),
        ),
        migrations.AlterField(
            model_name="listingimage",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Sıra"),
        ),
        migrations.AlterField(
            model_name="listingimage",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yüklenme Tarihi"
            ),
        ),
    ]
