# Generated by Django 5.2.7 on 2025-10-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_bannerimage_alt_text_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannerimage",
            name="alt_text_position",
            field=models.CharField(
                choices=[("left", "Sol"), ("center", "Orta"), ("right", "Sağ")],
                default="center",
                help_text="Alternatif metnin banner üzerindeki konumu",
                max_length=20,
                verbose_name="Alternatif Metin Konumu",
            ),
        ),
        migrations.AlterField(
            model_name="bannerimage",
            name="button_position",
            field=models.CharField(
                choices=[("left", "Sol"), ("center", "Orta"), ("right", "Sağ")],
                default="center",
                help_text="Butonun banner üzerindeki konumu",
                max_length=20,
                verbose_name="Buton Konumu",
            ),
        ),
    ]
