# Generated by Django 5.2.7 on 2025-10-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_alter_about_options_alter_construction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="google_analytics_id",
            field=models.CharField(
                blank=True,
                help_text="Google Analytics için izleme ID (örn: UA-XXXXXXXX-X veya G-XXXXXXXXXX)",
                max_length=50,
                verbose_name="Google Analytics ID",
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="google_search_console_verification",
            field=models.CharField(
                blank=True,
                help_text="Google Search Console için meta tag veya HTML doğrulama kodu",
                max_length=500,
                verbose_name="Google Search Console Doğrulama Kodu",
            ),
        ),
    ]
