# Generated by Django 5.2.7 on 2025-10-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_about_google_analytics_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="map_embed_code",
            field=models.TextField(
                blank=True,
                help_text="Google Maps embed kodunu buraya yapıştırın",
                verbose_name="Harita Embed Kodu",
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="map_latitude",
            field=models.CharField(
                blank=True,
                help_text="Harita konumunun enlem değeri",
                max_length=20,
                verbose_name="Enlem (Latitude)",
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="map_longitude",
            field=models.CharField(
                blank=True,
                help_text="Harita konumunun boylam değeri",
                max_length=20,
                verbose_name="Boylam (Longitude)",
            ),
        ),
    ]
