# Generated by Django 5.2.7 on 2025-10-13 17:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_alter_bannerimage_alt_text_position_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bannerimage",
            name="overlay_color",
        ),
    ]
