# Generated by Django 5.2.7 on 2025-10-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0004_remove_bannerimage_overlay_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Arama için telefon numarası (ör: 905551234567)",
                max_length=20,
                verbose_name="Telefon Numarası",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="phone_position",
            field=models.CharField(
                choices=[("left", "Sol"), ("right", "Sağ")],
                default="left",
                help_text="Telefon ikonunun ekranda görüneceği konum",
                max_length=10,
                verbose_name="Telefon İkon Konumu",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_phone",
            field=models.BooleanField(
                default=True,
                help_text="Sayfada telefon ikonunu göster/gizle",
                verbose_name="Telefon İkonunu Göster",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_whatsapp",
            field=models.BooleanField(
                default=True,
                help_text="Sayfada WhatsApp ikonunu göster/gizle",
                verbose_name="WhatsApp İkonunu Göster",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp için telefon numarası (ör: 905551234567)",
                max_length=20,
                verbose_name="WhatsApp Numarası",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp_position",
            field=models.CharField(
                choices=[("left", "Sol"), ("right", "Sağ")],
                default="right",
                help_text="WhatsApp ikonunun ekranda görüneceği konum",
                max_length=10,
                verbose_name="WhatsApp İkon Konumu",
            ),
        ),
    ]
