# Generated by Django 5.2.7 on 2025-10-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0004_about_map_embed_code_about_map_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="google_maps_api_key",
            field=models.CharField(
                blank=True,
                help_text="Google Maps API anahtarınızı buraya ekleyin",
                max_length=100,
                verbose_name="Google Maps API Anahtarı",
            ),
        ),
    ]
