# Generated by Django 5.2.7 on 2025-10-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0005_sitesettings_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="contact_email_recipients",
            field=models.TextField(
                blank=True,
                help_text="İletişim formundan gelen mesajların gönderileceği e-posta adresleri. Birden fazla e-posta için virgül ile ayırın (örn: email1@example.com, email2@example.com)",
                verbose_name="İletişim Formu Alıcı E-postaları",
            ),
        ),
    ]
