# Generated by Django 5.2.7 on 2025-10-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0005_about_google_maps_api_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={
                "verbose_name": "Ana Sayfa Ayarları",
                "verbose_name_plural": "Ana Sayfa Ayarları",
            },
        ),
        migrations.AddField(
            model_name="about",
            name="homepage_template",
            field=models.CharField(
                choices=[
                    ("template1", "Template 1 - Large Banner"),
                    ("template2", "Template 2 - Minimal"),
                    ("template3", "Template 3 - Featured Focus"),
                    ("template4", "Template 4 - Content Rich"),
                ],
                default="template1",
                help_text="Anasayfa için kullanılacak şablonu seçin",
                max_length=20,
                verbose_name="Anasayfa Şablonu",
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="show_about_section",
            field=models.BooleanField(
                default=True, verbose_name="Hakkımızda Bölümünü Göster"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="show_contact_info",
            field=models.BooleanField(
                default=True, verbose_name="İletişim Bilgilerini Göster"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="show_featured_listings",
            field=models.BooleanField(
                default=True, verbose_name="Öne Çıkan İlanları Göster"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="show_features_section",
            field=models.BooleanField(
                default=True, verbose_name="Özellikler Bölümünü Göster"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="show_mission_vision",
            field=models.BooleanField(
                default=True, verbose_name="Misyon/Vizyonu Göster"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="show_recent_listings",
            field=models.BooleanField(default=True, verbose_name="Son İlanları Göster"),
        ),
        migrations.AddField(
            model_name="about",
            name="show_search_bar",
            field=models.BooleanField(
                default=True, verbose_name="Arama Çubuğunu Göster"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="show_social_media",
            field=models.BooleanField(
                default=True, verbose_name="Sosyal Medya Bağlantılarını Göster"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="show_stats_section",
            field=models.BooleanField(
                default=True, verbose_name="İstatistikleri Göster"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="show_testimonials",
            field=models.BooleanField(
                default=True, verbose_name="Müşteri Yorumlarını Göster"
            ),
        ),
    ]
