# Generated by Django 5.2.7 on 2025-10-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0006_alter_about_options_about_homepage_template_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-posta"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=500, verbose_name="Adres"),
                ),
                (
                    "map_embed_code",
                    models.TextField(
                        blank=True,
                        help_text="Google Maps embed kodunu buraya yapıştırın",
                        verbose_name="Harita Embed Kodu",
                    ),
                ),
                (
                    "map_latitude",
                    models.CharField(
                        blank=True,
                        help_text="Harita konumunun enlem değeri",
                        max_length=20,
                        verbose_name="Enlem (Latitude)",
                    ),
                ),
                (
                    "map_longitude",
                    models.CharField(
                        blank=True,
                        help_text="Harita konumunun boylam değeri",
                        max_length=20,
                        verbose_name="Boylam (Longitude)",
                    ),
                ),
                (
                    "google_maps_api_key",
                    models.CharField(
                        blank=True,
                        help_text="Google Maps API anahtarınızı buraya ekleyin",
                        max_length=100,
                        verbose_name="Google Maps API Anahtarı",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, verbose_name="Facebook URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram URL"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="Twitter URL"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, verbose_name="LinkedIn URL"),
                ),
                (
                    "google_search_console_verification",
                    models.CharField(
                        blank=True,
                        help_text="Google Search Console için meta tag veya HTML doğrulama kodu",
                        max_length=500,
                        verbose_name="Google Search Console Doğrulama Kodu",
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Analytics için izleme ID (örn: UA-XXXXXXXX-X veya G-XXXXXXXXXX)",
                        max_length=50,
                        verbose_name="Google Analytics ID",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Ayarları",
                "verbose_name_plural": "Site Ayarları",
            },
        ),
    ]
