# Generated by Django 5.2.7 on 2025-10-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0006_sitesettings_contact_email_recipients"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="email_from",
            field=models.EmailField(
                blank=True,
                help_text="Gönderilen emaillerde görünecek gönderen adresi (genellikle SMTP kullanıcı adı ile aynı)",
                max_length=254,
                verbose_name="Gönderen Email Adresi",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="smtp_host",
            field=models.CharField(
                blank=True,
                default="smtp.gmail.com",
                help_text="Email gönderimi için SMTP sunucu adresi (örn: smtp.gmail.com)",
                max_length=100,
                verbose_name="SMTP Sunucu",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="smtp_password",
            field=models.CharField(
                blank=True,
                help_text="Gmail için: Google Hesabı → Güvenlik → 2 Adımlı Doğrulama → Uygulama Şifreleri ile oluşturun",
                max_length=200,
                verbose_name="SMTP Şifre (App Password)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="smtp_port",
            field=models.IntegerField(
                blank=True,
                default=587,
                help_text="SMTP sunucu portu (Gmail için: 587)",
                null=True,
                verbose_name="SMTP Port",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="smtp_use_tls",
            field=models.BooleanField(
                default=True,
                help_text="Email güvenliği için TLS kullan (Gmail için: Açık)",
                verbose_name="TLS Kullan",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="smtp_username",
            field=models.EmailField(
                blank=True,
                help_text="Email gönderimi için kullanılacak email adresi",
                max_length=254,
                verbose_name="SMTP Kullanıcı Adı (Email)",
            ),
        ),
    ]
