# Generated by Django 5.2.7 on 2025-10-11 22:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0007_sitesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Başlık")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alt Başlık"
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="İçerik")),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("text_only", "Sadece Metin"),
                            ("image_left", "Resim Solda"),
                            ("image_right", "Resim Sağda"),
                            ("image_center", "Resim Ortada"),
                            ("cards", "Kartlar"),
                        ],
                        default="text_only",
                        max_length=20,
                        verbose_name="Düzen",
                    ),
                ),
                (
                    "text_alignment",
                    models.CharField(
                        choices=[("left", "Sol"), ("center", "Orta"), ("right", "Sağ")],
                        default="left",
                        max_length=10,
                        verbose_name="Metin Hizalama",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="custom_sections/",
                        verbose_name="Ana Resim",
                    ),
                ),
                (
                    "image_alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Resim Alt Yazısı"
                    ),
                ),
                (
                    "card_title_1",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Kart 1 Başlık"
                    ),
                ),
                (
                    "card_content_1",
                    models.TextField(blank=True, verbose_name="Kart 1 İçerik"),
                ),
                (
                    "card_image_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="custom_sections/cards/",
                        verbose_name="Kart 1 Resim",
                    ),
                ),
                (
                    "card_title_2",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Kart 2 Başlık"
                    ),
                ),
                (
                    "card_content_2",
                    models.TextField(blank=True, verbose_name="Kart 2 İçerik"),
                ),
                (
                    "card_image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="custom_sections/cards/",
                        verbose_name="Kart 2 Resim",
                    ),
                ),
                (
                    "card_title_3",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Kart 3 Başlık"
                    ),
                ),
                (
                    "card_content_3",
                    models.TextField(blank=True, verbose_name="Kart 3 İçerik"),
                ),
                (
                    "card_image_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="custom_sections/cards/",
                        verbose_name="Kart 3 Resim",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        blank=True,
                        help_text="HEX renk kodu (örn: #ffffff)",
                        max_length=20,
                        verbose_name="Arka Plan Rengi",
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        blank=True,
                        help_text="HEX renk kodu (örn: #000000)",
                        max_length=20,
                        verbose_name="Metin Rengi",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Meta Başlık"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta Açıklama"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturma Tarihi",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Özel Bölüm",
                "verbose_name_plural": "Özel Bölümler",
                "ordering": ["order"],
            },
        ),
    ]
