# Generated by Django 5.2.7 on 2025-10-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0007_sitesettings_email_from_sitesettings_smtp_host_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seosettings",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="Sayfanın kanonik URL'si (opsiyonel, otomatik oluşturulur)",
                verbose_name="Canonical URL",
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Virgülle ayrılmış anahtar kelimeler (örn: emlak, gayrimenkul, satılık)",
                max_length=255,
                verbose_name="Meta Anahtar Kelimeler",
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="og_type",
            field=models.CharField(
                default="website",
                help_text="İçerik tipi (örn: website, article)",
                max_length=50,
                verbose_name="Open Graph Type",
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="robots",
            field=models.CharField(
                choices=[
                    (
                        "index,follow",
                        "Index, Follow - Sayfa indexlensin ve linkler takip edilsin",
                    ),
                    (
                        "noindex,follow",
                        "No Index, Follow - Sayfa indexlenmesin ama linkler takip edilsin",
                    ),
                    (
                        "index,nofollow",
                        "Index, No Follow - Sayfa indexlensin ama linkler takip edilmesin",
                    ),
                    (
                        "noindex,nofollow",
                        "No Index, No Follow - Sayfa indexlenmesin ve linkler takip edilmesin",
                    ),
                ],
                default="index,follow",
                help_text="Arama motoru botları için talimatlar",
                max_length=30,
                verbose_name="Robots Meta Tag",
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="twitter_card",
            field=models.CharField(
                default="summary_large_image",
                help_text="Twitter kartı tipi (summary, summary_large_image, player, app)",
                max_length=50,
                verbose_name="Twitter Card Tipi",
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="twitter_creator",
            field=models.CharField(
                blank=True,
                help_text="İçerik oluşturan Twitter kullanıcı adı",
                max_length=50,
                verbose_name="Twitter Creator",
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="twitter_site",
            field=models.CharField(
                blank=True,
                help_text="Twitter kullanıcı adı (örn: @emlak)",
                max_length=50,
                verbose_name="Twitter Site",
            ),
        ),
        migrations.AlterField(
            model_name="seosettings",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="Sosyal medya platformlarında paylaşıldığında görünen görsel (1200x630px önerilir)",
                null=True,
                upload_to="seo/",
                verbose_name="Open Graph Görseli",
            ),
        ),
    ]
