# Generated by Django 5.2.7 on 2025-10-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0008_customsection"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text="Tarayıcı sekmesinde görünen favicon (genellikle 32x32 piksel)",
                upload_to="site/",
                verbose_name="Favicon",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Sitenizin logosunu yükleyin",
                upload_to="site/",
                verbose_name="Site Logosu",
            ),
        ),
    ]
