# Generated by Django 5.2.7 on 2025-10-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "properties",
            "0008_seosettings_canonical_url_seosettings_meta_keywords_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                (
                    "subject",
                    models.CharField(max_length=200, verbose_name="E-posta Konusu"),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="HTML içerik kullanabilirsiniz", verbose_name="İçerik"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("scheduled", "Zamanlanmış"),
                            ("sending", "Gönderiliyor"),
                            ("sent", "Gönderildi"),
                            ("failed", "Başarısız"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Boş bırakılırsa hemen gönderilir",
                        null=True,
                        verbose_name="Gönderim Zamanı",
                    ),
                ),
                (
                    "sent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gönderilme Tarihi"
                    ),
                ),
                (
                    "total_recipients",
                    models.IntegerField(default=0, verbose_name="Toplam Alıcı"),
                ),
                (
                    "sent_count",
                    models.IntegerField(default=0, verbose_name="Gönderilen"),
                ),
                (
                    "failed_count",
                    models.IntegerField(default=0, verbose_name="Başarısız"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bülten",
                "verbose_name_plural": "Bültenler",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-posta"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ad Soyad")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Abonelik aktif mi?",
                        verbose_name="Aktif",
                    ),
                ),
                (
                    "subscribed_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Abone Olma Tarihi"
                    ),
                ),
                (
                    "unsubscribed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Abonelikten Çıkma Tarihi"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Adresi"
                    ),
                ),
                (
                    "unsubscribe_token",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Abonelik İptal Tokeni",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bülten Abonesi",
                "verbose_name_plural": "Bülten Aboneleri",
                "ordering": ["-subscribed_date"],
            },
        ),
        migrations.CreateModel(
            name="PopupSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Newsletter popup'ını göster",
                        verbose_name="Popup Aktif",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Bültenimize Abone Olun",
                        max_length=100,
                        verbose_name="Popup Başlığı",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="En son emlak fırsatları ve haberlerden haberdar olun.",
                        verbose_name="Popup Açıklaması",
                    ),
                ),
                (
                    "delay_seconds",
                    models.IntegerField(
                        default=3,
                        help_text="Popup kaç saniye sonra açılsın",
                        verbose_name="Gecikme (saniye)",
                    ),
                ),
                (
                    "show_on_mobile",
                    models.BooleanField(default=True, verbose_name="Mobilde Göster"),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="Abone Ol", max_length=50, verbose_name="Buton Metni"
                    ),
                ),
                (
                    "button_color",
                    models.CharField(
                        default="#007bff", max_length=7, verbose_name="Buton Rengi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter Popup Ayarları",
                "verbose_name_plural": "Newsletter Popup Ayarları",
            },
        ),
    ]
