# Generated by Django 5.2.7 on 2025-10-11 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0009_sitesettings_favicon_sitesettings_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="address",
        ),
        migrations.RemoveField(
            model_name="about",
            name="content",
        ),
        migrations.RemoveField(
            model_name="about",
            name="email",
        ),
        migrations.RemoveField(
            model_name="about",
            name="facebook_url",
        ),
        migrations.RemoveField(
            model_name="about",
            name="google_analytics_id",
        ),
        migrations.RemoveField(
            model_name="about",
            name="google_maps_api_key",
        ),
        migrations.RemoveField(
            model_name="about",
            name="google_search_console_verification",
        ),
        migrations.RemoveField(
            model_name="about",
            name="image_alt_text",
        ),
        migrations.RemoveField(
            model_name="about",
            name="instagram_url",
        ),
        migrations.RemoveField(
            model_name="about",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="about",
            name="main_image",
        ),
        migrations.RemoveField(
            model_name="about",
            name="map_embed_code",
        ),
        migrations.RemoveField(
            model_name="about",
            name="map_latitude",
        ),
        migrations.RemoveField(
            model_name="about",
            name="map_longitude",
        ),
        migrations.RemoveField(
            model_name="about",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="about",
            name="meta_title",
        ),
        migrations.RemoveField(
            model_name="about",
            name="mission",
        ),
        migrations.RemoveField(
            model_name="about",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="about",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="about",
            name="title",
        ),
        migrations.RemoveField(
            model_name="about",
            name="twitter_url",
        ),
        migrations.RemoveField(
            model_name="about",
            name="vision",
        ),
    ]
