# Generated by Django 5.2.7 on 2025-10-14 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0009_newsletter_newslettersubscriber_popupsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("info", "Bilgi"),
                            ("success", "Başarılı"),
                            ("warning", "Uyarı"),
                            ("error", "Hata"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="Log Tipi",
                    ),
                ),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "subscriber_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Abone Email",
                    ),
                ),
                (
                    "error_details",
                    models.TextField(
                        blank=True, null=True, verbose_name="Hata Detayları"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="properties.newsletter",
                        verbose_name="Bülten",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bülten Logu",
                "verbose_name_plural": "Bülten Logları",
                "ordering": ["-created_date"],
                "indexes": [
                    models.Index(
                        fields=["-created_date"], name="properties__created_2eb370_idx"
                    ),
                    models.Index(
                        fields=["newsletter", "-created_date"],
                        name="properties__newslet_5024e6_idx",
                    ),
                    models.Index(
                        fields=["log_type"], name="properties__log_typ_75f9ff_idx"
                    ),
                ],
            },
        ),
    ]
