# Generated by Django 5.2.7 on 2025-10-11 22:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0010_remove_about_address_remove_about_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="show_about_section",
        ),
        migrations.RemoveField(
            model_name="about",
            name="show_mission_vision",
        ),
    ]
