# Generated by Django 5.2.7 on 2025-10-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0010_newsletterlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscriber",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Opsiyonel telefon numarası",
                max_length=20,
                verbose_name="Telefon",
            ),
        ),
    ]
