# Generated by Django 5.2.7 on 2025-10-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0011_newslettersubscriber_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TRY", "₺ Türk Lirası"),
                    ("USD", "$ Amerikan Doları"),
                    ("EUR", "€ Euro"),
                    ("GBP", "£ İngiliz Sterlini"),
                    ("AED", "د.إ Birleşik Arap Emirlikleri Dirhemi"),
                    ("SAR", "ر.س Suudi Arabistan Riyali"),
                    ("RUB", "₽ Rus Rublesi"),
                ],
                default="TRY",
                help_text="Fiyat para birimi",
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Emlak fiyatı",
                max_digits=12,
                verbose_name="Fiyat",
            ),
        ),
    ]
