# Generated by Django 5.2.7 on 2025-10-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0012_alter_customsection_layout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customsection",
            name="layout",
            field=models.CharField(
                choices=[
                    ("text_only", "Sadece Metin"),
                    ("image_left", "Resim Solda"),
                    ("image_right", "Resim Sağda"),
                    ("image_center", "Resim Ortada"),
                    ("cards", "Kartlar"),
                    ("about_section", "Hakkımızda Bölümü"),
                    ("services", "Hizmetler"),
                ],
                default="text_only",
                max_length=20,
                verbose_name="Düzen",
            ),
        ),
    ]
