# Generated by Django 5.2.7 on 2025-10-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0012_listing_currency_alter_listing_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "home_label",
                    models.CharField(
                        default="Ana Sayfa",
                        help_text="Ana sayfa menü bağlantısı için görünen metin",
                        max_length=50,
                        verbose_name="Ana Sayfa Menü Etiketi",
                    ),
                ),
                (
                    "listings_label",
                    models.CharField(
                        default="İlanlar",
                        help_text="İlanlar sayfası menü bağlantısı için görünen metin",
                        max_length=50,
                        verbose_name="İlanlar Menü Etiketi",
                    ),
                ),
                (
                    "construction_label",
                    models.CharField(
                        default="İnşaatlar",
                        help_text="İnşaatlar sayfası menü bağlantısı için görünen metin",
                        max_length=50,
                        verbose_name="İnşaatlar Menü Etiketi",
                    ),
                ),
                (
                    "references_label",
                    models.CharField(
                        default="Referanslar",
                        help_text="Referanslar sayfası menü bağlantısı için görünen metin",
                        max_length=50,
                        verbose_name="Referanslar Menü Etiketi",
                    ),
                ),
                (
                    "contact_label",
                    models.CharField(
                        default="İletişim",
                        help_text="İletişim sayfası menü bağlantısı için görünen metin",
                        max_length=50,
                        verbose_name="İletişim Menü Etiketi",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Menü Etiketleri",
                "verbose_name_plural": "Menü Etiketleri",
            },
        ),
    ]
