# Generated by Django 5.2.7 on 2025-10-17 10:28

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0013_navigationsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.FileField(
                blank=True,
                help_text="Tarayıcı sekmesinde görünen favicon - Sadece .ico formatı kabul edilir (genellikle 32x32 piksel)",
                upload_to="site/",
                validators=[properties.models.validate_favicon],
                verbose_name="Favicon",
            ),
        ),
    ]
