# Generated by Django 5.2.7 on 2025-10-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0013_alter_customsection_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="visible_custom_sections",
            field=models.ManyToManyField(
                blank=True,
                help_text="Anasayfada gösterilmesini istediğiniz özel bölümleri seçin",
                to="properties.customsection",
                verbose_name="Görünür Özel Bölümler",
            ),
        ),
    ]
