# Generated by Django 5.2.7 on 2025-10-11 23:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0014_about_visible_custom_sections"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Banner olarak kullanılacak görsel",
                        upload_to="banner/",
                        verbose_name="Banner Görseli",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Görsel için erişilebilirlik metni",
                        max_length=255,
                        verbose_name="Alternatif Metin",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True,
                        help_text="Banner üzerinde gösterilecek buton metni (boş bırakılırsa buton gösterilmez)",
                        max_length=100,
                        verbose_name="Buton Metni",
                    ),
                ),
                (
                    "button_link",
                    models.URLField(
                        blank=True,
                        help_text="Butonun yönlendireceği URL",
                        verbose_name="Buton Bağlantısı",
                    ),
                ),
                (
                    "button_position",
                    models.CharField(
                        choices=[
                            ("top-left", "Üst Sol"),
                            ("top-center", "Üst Orta"),
                            ("top-right", "Üst Sağ"),
                            ("middle-left", "Orta Sol"),
                            ("middle-center", "Orta"),
                            ("middle-right", "Orta Sağ"),
                            ("bottom-left", "Alt Sol"),
                            ("bottom-center", "Alt Orta"),
                            ("bottom-right", "Alt Sağ"),
                        ],
                        default="middle-center",
                        help_text="Butonun banner üzerindeki konumu",
                        max_length=20,
                        verbose_name="Buton Konumu",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturma Tarihi",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Banner Görseli",
                "verbose_name_plural": "Banner Görselleri",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="about",
            name="banner_images",
            field=models.ManyToManyField(
                blank=True,
                help_text="Anasayfa banner'ında gösterilmesini istediğiniz görselleri seçin",
                to="properties.bannerimage",
                verbose_name="Banner Görselleri",
            ),
        ),
    ]
