# Generated by Django 5.2.7 on 2025-10-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0015_bannerimage_about_banner_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannerimage",
            name="image",
            field=models.ImageField(
                help_text="Banner olarak kullanılacak görsel. Önerilen boyut: 1920x1080 piksel (16:9 en-boy oranı). Tüm banner görselleri aynı boyutta olmalıdır.",
                upload_to="banner/",
                verbose_name="Banner Görseli",
            ),
        ),
    ]
