# Generated by Django 5.2.7 on 2025-10-12 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0016_alter_bannerimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Başlık")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alt Başlık"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="references/",
                        verbose_name="Resim",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="references/videos/",
                        verbose_name="Video",
                    ),
                ),
                (
                    "image_alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Resim Alt Yazısı"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturma Tarihi",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Referans",
                "verbose_name_plural": "Referanslar",
                "ordering": ["order"],
            },
        ),
    ]
