# Generated by Django 5.2.7 on 2025-10-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0017_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="show_construction_page",
            field=models.BooleanField(
                default=True,
                help_text="Header menüsünde İnşaatlar sayfası linkini göster",
                verbose_name="İnşaatlar Sayfasını Göster",
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="show_contact_page",
            field=models.BooleanField(
                default=True,
                help_text="Header menüsünde İletişim sayfası linkini göster",
                verbose_name="İletişim Sayfasını Göster",
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="show_listings_page",
            field=models.BooleanField(
                default=True,
                help_text="Header menüsünde İlanlar sayfası linkini göster",
                verbose_name="İlanlar Sayfasını Göster",
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="show_references_page",
            field=models.BooleanField(
                default=True,
                help_text="Header menüsünde Referanslar sayfası linkini göster",
                verbose_name="Referanslar Sayfasını Göster",
            ),
        ),
    ]
