# Generated by Django 5.2.7 on 2025-10-12 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "properties",
            "0018_about_show_construction_page_about_show_contact_page_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reference",
            name="image",
        ),
        migrations.RemoveField(
            model_name="reference",
            name="image_alt_text",
        ),
        migrations.RemoveField(
            model_name="reference",
            name="video",
        ),
        migrations.CreateModel(
            name="ReferenceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="references/images/", verbose_name="Resim"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alternatif Metin"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.reference",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referans Resmi",
                "verbose_name_plural": "Referans Resimleri",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ReferenceVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to="references/videos/", verbose_name="Video"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Video Başlığı"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="properties.reference",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referans Videosu",
                "verbose_name_plural": "Referans Videoları",
                "ordering": ["order"],
            },
        ),
    ]
