# Generated by Django 5.2.7 on 2025-10-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0019_remove_reference_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="tax_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Vergi Numarası"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="tax_office",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Vergi Dairesi"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone",
            field=models.CharField(blank=True, max_length=200, verbose_name="Telefon"),
        ),
    ]
